language: go

go:
  - tip

script:
  - errcheck ./...
  - go-errorlint ./...
  - gocognit -over 10 . cmd/*
  - staticcheck ./...
  - golint ./...
  - deadcode . cmd/*
  - go test -v -short -covermode=count -coverprofile=coverage.out

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get -u -v github.com/polyfloyd/go-errorlint
  - go get -u -v github.com/uudashr/gocognit/cmd/gocognit
  - go get -u -v honnef.co/go/tools/cmd/staticcheck
  - go get -u -v golang.org/x/lint/golint
  - go get -u -v github.com/kisielk/errcheck
  - go get -u -v github.com/tsenart/deadcode

